CREATE DATABASE AquaMate;
USE AquaMate;
ALTER DATABASE AquaMate CHARACTER SET utf8;

CREATE TABLE Usuario (
	Usuario_ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Dados_Usuario (
	Dados_Usuario_ID INT AUTO_INCREMENT PRIMARY KEY
);